# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160612_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='days',
            field=models.CharField(choices=[('1', 'a full day'), ('0.5', 'half a day')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workday',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
