# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160703_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['projectName']},
        ),
        migrations.AlterField(
            model_name='workday',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
