# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160713_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_units',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=255),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
